-- MySQL Script generated by MySQL Workbench
-- 06/01/16 18:52:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prols
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `prols` ;

-- -----------------------------------------------------
-- Schema prols
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prols` DEFAULT CHARACTER SET utf8 ;
USE `prols` ;

-- -----------------------------------------------------
-- Table `prols`.`emp_acc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`emp_acc` ;

CREATE TABLE IF NOT EXISTS `prols`.`emp_acc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `ip_add` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prols`.`emp_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`emp_profile` ;

CREATE TABLE IF NOT EXISTS `prols`.`emp_profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_acc_acc_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `mname` VARCHAR(45) NOT NULL,
  `bday` DATETIME NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `gender` CHAR(10) NOT NULL,
  `img_path` VARCHAR(45) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_emp_profile_emp_acc`
    FOREIGN KEY (`emp_acc_acc_id`)
    REFERENCES `prols`.`emp_acc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_emp_profile_emp_acc_idx` ON `prols`.`emp_profile` (`emp_acc_acc_id` ASC);


-- -----------------------------------------------------
-- Table `prols`.`list_dept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`list_dept` ;

CREATE TABLE IF NOT EXISTS `prols`.`list_dept` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dept_names` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prols`.`list_pos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`list_pos` ;

CREATE TABLE IF NOT EXISTS `prols`.`list_pos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pos_names` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prols`.`emp_work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`emp_work` ;

CREATE TABLE IF NOT EXISTS `prols`.`emp_work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `list_dept_dept_id` INT NOT NULL,
  `list_pos_pos_id` INT NOT NULL,
  `emp_acc_acc_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_emp_work_list_dept1`
    FOREIGN KEY (`list_dept_dept_id`)
    REFERENCES `prols`.`list_dept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_work_list_pos1`
    FOREIGN KEY (`list_pos_pos_id`)
    REFERENCES `prols`.`list_pos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_work_emp_acc1`
    FOREIGN KEY (`emp_acc_acc_id`)
    REFERENCES `prols`.`emp_acc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_emp_work_list_dept1_idx` ON `prols`.`emp_work` (`list_dept_dept_id` ASC);

CREATE INDEX `fk_emp_work_list_pos1_idx` ON `prols`.`emp_work` (`list_pos_pos_id` ASC);

CREATE INDEX `fk_emp_work_emp_acc1_idx` ON `prols`.`emp_work` (`emp_acc_acc_id` ASC);


-- -----------------------------------------------------
-- Table `prols`.`list_cont_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`list_cont_types` ;

CREATE TABLE IF NOT EXISTS `prols`.`list_cont_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prols`.`emp_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`emp_contact` ;

CREATE TABLE IF NOT EXISTS `prols`.`emp_contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact` VARCHAR(45) NOT NULL,
  `emp_profile_id` INT NOT NULL,
  `list_cont_types_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_emp_contact_emp_profile1`
    FOREIGN KEY (`emp_profile_id`)
    REFERENCES `prols`.`emp_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_contact_list_cont_types1`
    FOREIGN KEY (`list_cont_types_id`)
    REFERENCES `prols`.`list_cont_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_emp_contact_emp_profile1_idx` ON `prols`.`emp_contact` (`emp_profile_id` ASC);

CREATE INDEX `fk_emp_contact_list_cont_types1_idx` ON `prols`.`emp_contact` (`list_cont_types_id` ASC);


-- -----------------------------------------------------
-- Table `prols`.`list_leave_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`list_leave_type` ;

CREATE TABLE IF NOT EXISTS `prols`.`list_leave_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `leave_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prols`.`emp_leave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`emp_leave` ;

CREATE TABLE IF NOT EXISTS `prols`.`emp_leave` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `request` VARCHAR(100) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `date_started` DATETIME NOT NULL,
  `date_ended` DATETIME NOT NULL,
  `emp_acc_id` INT NOT NULL,
  `list_leave_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_emp_leave_emp_acc1`
    FOREIGN KEY (`emp_acc_id`)
    REFERENCES `prols`.`emp_acc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_leave_list_leave_type1`
    FOREIGN KEY (`list_leave_type_id`)
    REFERENCES `prols`.`list_leave_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_emp_leave_emp_acc1_idx` ON `prols`.`emp_leave` (`emp_acc_id` ASC);

CREATE INDEX `fk_emp_leave_list_leave_type1_idx` ON `prols`.`emp_leave` (`list_leave_type_id` ASC);


-- -----------------------------------------------------
-- Table `prols`.`emp_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`emp_time` ;

CREATE TABLE IF NOT EXISTS `prols`.`emp_time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time_in` DATETIME NOT NULL,
  `time_out` DATETIME NOT NULL,
  `ip_add` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `emp_acc_acc_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_emp_time_emp_acc1`
    FOREIGN KEY (`emp_acc_acc_id`)
    REFERENCES `prols`.`emp_acc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_emp_time_emp_acc1_idx` ON `prols`.`emp_time` (`emp_acc_acc_id` ASC);


-- -----------------------------------------------------
-- Table `prols`.`emp_approval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`emp_approval` ;

CREATE TABLE IF NOT EXISTS `prols`.`emp_approval` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `request` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `ip_add` VARCHAR(45) NOT NULL,
  `emp_time_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_emp_approval_emp_time1`
    FOREIGN KEY (`emp_time_id`)
    REFERENCES `prols`.`emp_time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_emp_approval_emp_time1_idx` ON `prols`.`emp_approval` (`emp_time_id` ASC);


-- -----------------------------------------------------
-- Table `prols`.`list_holidays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`list_holidays` ;

CREATE TABLE IF NOT EXISTS `prols`.`list_holidays` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prols`.`list_ip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `prols`.`list_ip` ;

CREATE TABLE IF NOT EXISTS `prols`.`list_ip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `allowed_ip` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
